// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtZV0sMtAqkj0EIqFw8ROAF7r1nS8X74',
    appId: '1:1021918771595:web:d95db7e3b821cfc239578e',
    messagingSenderId: '1021918771595',
    projectId: 'flexana-test',
    authDomain: 'flexana-test.firebaseapp.com',
    storageBucket: 'flexana-test.firebasestorage.app',
    measurementId: 'G-DH6TCCBC12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRrLdKGeBvBIyENbZMV747FbxVo8E_f0g',
    appId: '1:1021918771595:android:5adc99592b96a74b39578e',
    messagingSenderId: '1021918771595',
    projectId: 'flexana-test',
    storageBucket: 'flexana-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB0571Nd4AZ-K38UO4vzQbcKo16bq8XAs',
    appId: '1:1021918771595:ios:63562062283d4bf339578e',
    messagingSenderId: '1021918771595',
    projectId: 'flexana-test',
    storageBucket: 'flexana-test.firebasestorage.app',
    iosBundleId: 'com.example.flexana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB0571Nd4AZ-K38UO4vzQbcKo16bq8XAs',
    appId: '1:1021918771595:ios:63562062283d4bf339578e',
    messagingSenderId: '1021918771595',
    projectId: 'flexana-test',
    storageBucket: 'flexana-test.firebasestorage.app',
    iosBundleId: 'com.example.flexana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKtZV0sMtAqkj0EIqFw8ROAF7r1nS8X74',
    appId: '1:1021918771595:web:7e0c4ad7c155bd1839578e',
    messagingSenderId: '1021918771595',
    projectId: 'flexana-test',
    authDomain: 'flexana-test.firebaseapp.com',
    storageBucket: 'flexana-test.firebasestorage.app',
    measurementId: 'G-K3KBJ6VSQL',
  );
}
